os:
  - windows
  - linux
  - osx

env:
  - YARN_GPG=no # Fixes build on Windows

language: node_js

node_js:
  - "20"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - jest --coverage --testPathIgnorePatterns test-app
  - cd test-app && yarn test && yarn e2e && cd ..
  - npm prettier --check "**/*.{js,jsx,json,css,scss,html,md,yml}"
  - npm eslint --ext .js lib/
  - cat ./coverage/lcov.info | coveralls
